#!/bin/bash

# get the current time and set a background depending
# on the result

cur_time=$(date +"%H")

if [[ 0 -le "$cur_time" && "$cur_time" -le 6 ]]
then
	/home/thewalla07/bin/set-night-bg
elif [[ 7 -le "$cur_time" && "$cur_time" -le 11 ]]
then
	/home/thewalla07/bin/set-morning-bg
elif [[ 12 -le "$cur_time" && "$cur_time" -le 16 ]]
then
	/home/thewalla07/bin/set-noon-bg
elif [[ 17 -le "$cur_time" && "$cur_time" -le 18 ]]
then
	/home/thewalla07/bin/set-evening-bg
elif [[ 19 -le "$cur_time" && "$cur_time" -le 23 ]]
then
	/home/thewalla07/bin/set-night-bg
fi

