#!/bin/bash

# I have a crontab that runs this script every hour 
# and on reboots to set the appropriate wallpaper 
# for the time of day

# get the current time and set a background depending
# on the result

cur_time=$(date +"%H")

if ((0<=cur_time && cur_time<=6))
then
	/home/thewalla07/bin/set-night-bg
elif ((7<=cur_time && cur_time<=11))
then
	/home/thewalla07/bin/set-morning-bg
elif ((12<=cur_time && cur_time<=16))
then
	/home/thewalla07/bin/set-noon-bg
elif ((17<=cur_time && cur_time<=18))
then
	/home/thewalla07/bin/set-evening-bg
elif ((19<=cur_time && cur_time<=23))
then
	/home/thewalla07/bin/set-night-bg
fi

