#!/bin/bash

# get the current time and set a background depending
# on the result

cur_time=$(date +"%H")

if [[ 0 -lt "$cur_time" && "$cur_time" -lt 6 ]]
then
	/home/thewalla07/bin/set-night-bg
elif [[ 7 -lt "$cur_time" && "$cur_time" -lt 11 ]]
then
	/home/thewalla07/bin/set-morning-bg
elif [[ 12 -lt "$cur_time" && "$cur_time" -lt 16 ]]
then
	/home/thewalla07/bin/set-noon-bg
elif [[ 17 -lt "$cur_time" && "$cur_time" -lt 18 ]]
then
	/home/thewalla07/bin/set-evening-bg
elif [[ 19 -lt "$cur_time" && "$cur_time" -lt 23 ]]
then
	/home/thewalla07/bin/set-night-bg
fi

